spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: 0b16e5f5488cc0262219d50ab7b0d03c
            client-secret: 0QOlXVhoDMiNByBovTSDswKLVjuwE8yW
            scope: profile_nickname, account_email, profile_image
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-name: Kakao
          naver:
            authorization-grant-type: authorization_code
            client-id: KPMa4eG4NYGPpyHqHKu9
            client-secret: VkTY0z6Yt4
            scope: profile_nickname, account_email, profile_image
            redirect-uri: ${NAVER_REDIRECT_URI}
            client-name: Naver
          google:
            authorization-grant-type: authorization_code
            client-id: 955629770798-q9qt164df7p1ja5dr9mott5f3jklkgis.apps.googleusercontent.com
            client-secret: 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
            scope: profile_nickname, account_email, profile_image
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            client-name: Google
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-name-attribute: id
            user-info-uri: https://kapi.kakao.com/v2/user/me
            authorization-uri: https://kauth.kakao.com/oauth/authorize
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  application:
    name: devlog

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_HOST}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    user:
      name: admin
      password: admin

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  type-aliases-package: org.bitcamp.devlog.dto
  mapper-locations: classpath:mapper/*.xml